### ISSUE TITLE
one test is creating a plot window

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rsbeams#23]
The plot window has to be closed manually.
This needs to be fixed.

**Comment by JohanCar1sson** [comment]
The culprit is not one of the tests, but rather examples/test_sample.py, which pytest executes by default (based on the filename). My preferred solution would be to add a pytest.ini config file that excludes the examples subdir from the test search path. However, pytest.ini is listed in .gitignore.

What is the RadiaSoft way of using pytest? Should pytest execute every script with a matching name, or only those in the tests subdir?

**Comment by JohanCar1sson** [comment]
The solution is thus to not invoke pytest directly, but through "python setup.py test".

Thanks @robnagler
